[tool.poetry]
name = "test"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
twilio = "9.4.6"
sendgrid = "6.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
